name: SonarQube Analysis

on:
  [push]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=identity --cov-report=xml

      - name: Run SonarQube Scanner
        run: |
          docker run --rm \
            -v "$(pwd):/usr/src" \
            sonarsource/sonar-scanner-cli